config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :users, only: :none do
      resources :store_credits, only: [:index]
      resources :credits, only: [:new, :create, :show], controller: :store_credits, type: 'credits'
      resources :debits, only: [:new, :create, :show], controller: :store_credits, type: 'debits'
    end

    resources :store_credits, only: [:index]
  end
end

app/models/spree/store_credit.rb
module Spree
  class StoreCredit < ActiveRecord::Base
    attr_accessor :disable_negative_payment_mode

    belongs_to :transactioner, class_name: Spree.user_class

    validates :amount, :user_id, :reason, :type, :balance, :transaction_id, presence: true
    validates :amount, :balance, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    validates :transaction_id, uniqueness: true, allow_blank: true

    belongs_to :user, class_name: Spree.user_class

    before_validation :generate_transaction_id, on: :create
    before_create :update_user_wallet

    scope :order_created_at_desc, -> { order('created_at desc') }

    private
      def update_user_wallet
        user.update_attribute(:store_credits_total, balance)
      end

      def generate_transaction_id
        begin
          self.transaction_id = (Time.now.strftime("%s") + rand(999999).to_s).to(15)
        end while Spree::StoreCredit.exists?(transaction_id: transaction_id)
      end
  end
end

app/controllers/spree/admin/store_credits_controller.rb
module Spree
  module Admin
    class StoreCreditsController < ResourceController
      helper_method :store_credit_class
      skip_before_filter :load_resource, :only => [:index]
      before_filter :disable_negative_payment_mode, :add_transactioner_to_store_credit, :only => :create

      def index
        @search = association_or_class.order_created_at_desc.ransack(params[:q])
        @store_credits = @search.result.page(params[:page]).includes(required_includes_arguements)
      end

      protected

        def disable_negative_payment_mode
          @store_credit.disable_negative_payment_mode = true
        end

        def add_transactioner_to_store_credit
          @store_credit.transactioner = spree_current_user
        end

        def self.parent_data
          { :model_class => Spree.user_class, :find_by => :id, :model_name => 'spree/user' }
        end

        def association_or_class
          parent ? parent.store_credits : Spree::StoreCredit
        end

        def required_includes_arguements
          parent ? :transactioner : [:transactioner, :user]
        end

        def build_resource
          if parent_data.present?
            store_credit_class.new{ |store_credit| store_credit.user = parent }
          else
            store_credit_class.new
          end
        end

        def find_resource
          if parent_data.present?
            store_credit_class.where(:id => params[:id], :user_id => parent.id).first
          else
            store_credit_class.where(:id => params[:id]).first
          end
        end

        def store_credit_class
          params[:type] ? "spree/#{params[:type]}".classify.constantize : model_class
        end
    end
  end
end

app/views/spree/admin/store_credits/index.html.erb
<%= render partial: 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
    <div data-hook="admin_store_credits_index_search">
      <%= search_form_for [:admin, @search] do |f| %>
        <div class="alpha nine columns">
          <div class="field">
            <%= f.label :transaction_id_eq, Spree.t(:transaction_id) %>
            <%= f.text_field :transaction_id_eq %>
          </div>

          <div class="field">
            <%= f.label :transactioner_email_cont, Spree.t(:transactioner_email) %>
            <%= f.email_field :transactioner_email_cont %>
          </div>

          <% unless @user %>
            <div class="field">
              <%= f.label :user_email_cont, Spree.t(:user_email) %>
              <%= f.email_field :user_email_cont %>
            </div>
          <% end %>
        </div>

      <div class="clear"></div>

      <div class="form-buttons actions filter-actions" data-hook="admin_products_index_search_buttons">
        <%= button Spree.t(:search), 'icon-search' %>
      </div>
      <% end %>
    </div>
<% end %>

<% content_for :page_title do %>
  <% if @user %>
    <%= Spree.t(:store_credits_for_user_email, user_email: @user.email) %> (<%= Spree.t(:current_balance_for_user, total: @user.store_credits_total) %>)
  <% else %>
    <%= Spree.t(:listing_store_credits) %>
  <% end %>
<% end %>

<% if @user %>
  <% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_credit), new_admin_user_credit_path(user_id: @user), class: "btn-success", icon: 'add' %>
    <%= button_link_to Spree.t(:new_debit), new_admin_user_debit_path(user_id: @user), class: "btn-success", icon: 'add' %>
  <% end %>
<% end %>

<%= paginate @store_credits %>

<table class="table index" id="transaction_listing" data-hook>
  <thead>
    <tr data-hook="transactions_index_headers">
      <th><%= sort_link @search, :transaction_id, Spree.t(:transaction_number) %></th>
      <% unless @user %>
        <th class="actions"><%= sort_link @search, :user_email, Spree.t(:user) %></th>
      <% end %>
      <th class="actions"><%= sort_link @search, :transactioner_email, Spree.t(:transactioner_email) %></th>
      <th class="actions"><%= sort_link @search, :amount, Spree.t(:amount) %></th>
      <th class="actions"><%= sort_link @search, :balance, Spree.t(:balance) %></th>
      <% if @user %>
        <th class="actions"><%= sort_link @search, :reason, Spree.t(:reason) %></th>
        <th class="actions"><%= sort_link @search, :payment_mode, Spree.t(:payment_mode) %></th>
      <% end %>
      <th class="actions"><%= sort_link @search, :type, Spree.t(:type) %></th>
      <% unless @user %>
        <th data-hook="admin_users_index_header_actions" class="actions"><%= Spree.t(:action) %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @store_credits.each do |store_credit|%>
      <tr id="<%= cycle('odd', 'even') %>" data-hook="transactions_index_rows">
        <td class="align-center"><%= store_credit.transaction_id %></td>
        <% unless @user %>
          <td class="align-center"><%= link_to store_credit.user.email, admin_user_path(store_credit.user) %></td>
        <% end %>
        <td class="align-center"><%= store_credit.transactioner.try(:email) %></td>
        <td class="align-center"><%= number_to_currency store_credit.amount %></td>
        <td class="align-center"><%= number_to_currency store_credit.balance %></td>
        <% if @user %>
          <td class="align-center"><%= store_credit.reason %></td>
          <td class="align-center"><%= store_credit.class::PAYMENT_MODE.key(store_credit.payment_mode) %>
        <% end %>
        <td class="align-center"><%= store_credit.type.demodulize %></td>
        <% unless @user %>
          <td><%= link_to Spree.t(:credit), new_admin_user_credit_path(user_id: store_credit.user) %> | <%= link_to Spree.t(:debit), new_admin_user_debit_path(user_id: store_credit.user) %> | <%= link_to Spree.t(:view), admin_user_store_credits_path(user_id: store_credit.user) %></td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/spree/admin/store_credits/new.html.erb
<%= render partial: 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t("new_store_#{@store_credit.type.demodulize.downcase}")%>
<% end %>

<%= render 'spree/shared/error_messages', target: @store_credit %>

<h4 data-hook='user-email'>User Email: <%= @store_credit.user.email %></h3>
<h4 data-hook='user-email'>Current Balance: <%= @store_credit.user.store_credits_total %></h4>

<div data-hook="transactions_new_form">
  <%= form_for [:admin, @user, @store_credit], as: :store_credit do |f| %>
    <%= f.field_container :amount, class: ['form-group'] do %>
      <%= f.label :amount %>*<br />
      <%= f.text_field :amount, id: "debit_credit_amount", class: 'form-control' %>
    <% end %>

    <%= f.field_container :payment_mode, class: ['form-group'] do %>
      <%= f.label :payment_mode, 'Payment Mode' %>*<br />
      <%= f.select :payment_mode, store_credit_class::PAYMENT_MODE.select { |key, value| value >= 0 }, { prompt: 'Select' }, class: 'select2' %>
    <% end %>

    <%= f.field_container :reason, class: ['form-group'] do %>
      <%= f.label :reason %>*<br />
      <%= f.text_field :reason, class: 'form-control' %>
    <% end %>

    <%= f.submit :commit, value: @store_credit.type.demodulize, class: 'button', id: 'debit_credit' %>
  <% end %>
</div>